# monitoring/prometheus.yml
#
# Configuration de Prometheus pour le projet ValorisationDonneeMeteo.
# Prometheus scrape les métriques de ton backend Django toutes les 15 secondes.

global:
  scrape_interval: 15s # À quelle fréquence on collecte les métriques
  evaluation_interval: 15s # À quelle fréquence on évalue les règles d'alerte
  scrape_timeout: 10s

  # Labels ajoutés à toutes les métriques (utile pour distinguer les envs)
  external_labels:
    env: "dev"
    project: "valorisation-donnee-meteo"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "django-backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "backend-django"
  - job_name: "frontend"
    static_configs:
      - targets: ["frontend:3000"]
